steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/defi-pipeline:latest', '.']
  
  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/defi-pipeline:latest']
  
images:
  - 'gcr.io/$PROJECT_ID/defi-pipeline:latest'
