CREATE TABLE allocation_parameters (
    run_id UUID PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    tvl_limit_percentage DECIMAL(5, 4),
    max_alloc_percentage DECIMAL(5, 4),
    conversion_rate DECIMAL(20, 10),
    min_pools INTEGER,
    profit_optimization BOOLEAN,
    approved_tokens_snapshot JSONB,
    blacklisted_tokens_snapshot JSONB,
    approved_protocols_snapshot JSONB,
    icebox_tokens_snapshot JSONB,
    token_marketcap_limit DECIMAL(20, 2),
    pool_tvl_limit DECIMAL(20, 2),
    pool_apy_limit DECIMAL(20, 4),
    pool_pair_tvl_ratio_min DECIMAL(5, 4),
    pool_pair_tvl_ratio_max DECIMAL(5, 4),
    group1_max_pct DECIMAL(5, 4),
    group2_max_pct DECIMAL(5, 4),
    group3_max_pct DECIMAL(5, 4),
    position_max_pct_total_assets DECIMAL(5, 4),
    position_max_pct_pool_tvl DECIMAL(5, 4),
    group1_apy_delta_max DECIMAL(20, 4),
    group1_7d_stddev_max DECIMAL(20, 4),
    group1_30d_stddev_max DECIMAL(20, 4),
    group2_apy_delta_max DECIMAL(20, 4),
    group2_7d_stddev_max DECIMAL(20, 4),
    group2_30d_stddev_max DECIMAL(20, 4),
    group3_apy_delta_min DECIMAL(20, 4),
    group3_7d_stddev_min DECIMAL(20, 4),
    group3_30d_stddev_min DECIMAL(20, 4),
    other_dynamic_limits JSONB,
    icebox_ohlc_l_threshold_pct DECIMAL(5, 4),
    icebox_ohlc_l_days_threshold INTEGER,
    icebox_ohlc_c_threshold_pct DECIMAL(5, 4),
    icebox_ohlc_c_days_threshold INTEGER,
    icebox_recovery_l_days_threshold INTEGER,
    icebox_recovery_c_days_threshold INTEGER
);