CREATE TABLE blacklisted_tokens (
    id SERIAL PRIMARY KEY,
    token_symbol VARCHAR(255) NOT NULL UNIQUE,
    added_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    removed_timestamp TIMESTAMP WITH TIME ZONE
);